-- Fix critical schema mismatches discovered in codebase review
-- This migration adds missing columns and fixes constraints

-- ============================================================================
-- Fix #1: Add missing columns to generated_content table
-- ============================================================================

-- Add columns that application code expects but don't exist in schema
ALTER TABLE generated_content ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE generated_content ADD COLUMN IF NOT EXISTS suggested_keywords TEXT[];
ALTER TABLE generated_content ADD COLUMN IF NOT EXISTS estimated_reading_time INT;
ALTER TABLE generated_content ADD COLUMN IF NOT EXISTS hero_image_url TEXT;

COMMENT ON COLUMN generated_content.meta_description IS 'SEO meta description generated by AI';
COMMENT ON COLUMN generated_content.suggested_keywords IS 'Array of suggested keywords for content optimization';
COMMENT ON COLUMN generated_content.estimated_reading_time IS 'Estimated reading time in minutes';
COMMENT ON COLUMN generated_content.hero_image_url IS 'URL to hero image (DALL-E generated or uploaded to Supabase Storage)';

-- ============================================================================
-- Fix #2: Update status enum to match application logic
-- ============================================================================

-- Drop old constraint that only allowed 'draft' and 'published'
ALTER TABLE generated_content DROP CONSTRAINT IF EXISTS generated_content_status_check;

-- Add new constraint with full workflow: draft → pending_approval → approved → published
-- Also allows 'rejected' status for content that doesn't meet standards
ALTER TABLE generated_content ADD CONSTRAINT generated_content_status_check
  CHECK (status IN ('draft', 'pending_approval', 'approved', 'published', 'rejected'));

COMMENT ON COLUMN generated_content.status IS 'Content workflow status: draft → pending_approval → approved → published (or rejected)';

-- ============================================================================
-- Fix #3: Prevent race condition in concurrent analyses
-- ============================================================================

-- Create exclusion constraint to prevent multiple in-progress analyses per project
-- This is atomic at database level, preventing race conditions in application code
ALTER TABLE website_analyses
ADD CONSTRAINT one_analysis_in_progress_per_project
EXCLUDE (project_id WITH =) WHERE (status = 'in_progress');

COMMENT ON CONSTRAINT one_analysis_in_progress_per_project ON website_analyses IS 'Ensures only one analysis can be in progress per project at a time, preventing race conditions';

-- ============================================================================
-- Fix #4: Add missing RLS constraint for default pattern deletion
-- ============================================================================

-- Drop existing delete policy
DROP POLICY IF EXISTS "Users can delete exclusion patterns for own projects" ON crawler_exclusion_patterns;

-- Recreate with constraint to prevent deletion of system defaults
CREATE POLICY "Users can delete exclusion patterns for own projects"
  ON crawler_exclusion_patterns FOR DELETE
  USING (
    is_default = false AND  -- Can only delete custom patterns, not system defaults
    EXISTS (
      SELECT 1 FROM projects
      WHERE projects.id = crawler_exclusion_patterns.project_id
      AND projects.user_id = auth.uid()
    )
  );

COMMENT ON POLICY "Users can delete exclusion patterns for own projects" ON crawler_exclusion_patterns IS 'Users can only delete custom patterns (not system defaults) for their own projects';

-- ============================================================================
-- Verification queries (commented out, uncomment to test)
-- ============================================================================

-- Verify generated_content columns exist
-- SELECT column_name, data_type
-- FROM information_schema.columns
-- WHERE table_name = 'generated_content'
-- ORDER BY ordinal_position;

-- Verify status constraint
-- SELECT constraint_name, check_clause
-- FROM information_schema.check_constraints
-- WHERE constraint_name LIKE '%generated_content_status%';

-- Verify exclusion constraint
-- SELECT conname, pg_get_constraintdef(oid)
-- FROM pg_constraint
-- WHERE conname = 'one_analysis_in_progress_per_project';

-- Test race condition prevention (should fail on second insert)
-- BEGIN;
-- INSERT INTO website_analyses (project_id, status) VALUES ('test-project-id', 'in_progress');
-- INSERT INTO website_analyses (project_id, status) VALUES ('test-project-id', 'in_progress'); -- Should fail
-- ROLLBACK;
